allowBuilds:
  '@parcel/watcher': true
  '@sentry/cli': true
  '@swc/core': true
  bufferutil: true
  core-js: true
  esbuild: true
  lefthook: true
  utf-8-validate: true
shellEmulator: true

trustPolicy: no-downgrade
packages:
  - .
overrides:
  fast-uri: '>=3.1.7'
