name: Release

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
    branches:
      - main

jobs:
  release:
    strategy:
      matrix:
        node-version: [24.x]

    name: Create a new release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: vars.ENABLE_SEMANTIC_RELEASE == 'true' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'

    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0

      - name: Recreate trusted main branch at tested SHA
        run: git checkout -B main "${{ github.event.workflow_run.head_sha }}"

      - name: Set up Node.js environment
        uses: ./.github/actions/setup-project
        with:
          node-version: ${{ matrix.node-version }}

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: pnpm audit --prod --audit-level high

      - name: Release
        run: pnpm exec semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
